### ISSUE TITLE
link出现问题

### ISSUE THREAD

**Issue by yexiang1994** [sunnylqm/react-native-storage#231]
link的时候出现问了，不能link
@react-native-community/async-storage： "^1.6.1",
react-native-storage: "^1.0.1"

 react-native link @react-native-community/async-storage
rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?

Cannot read property '_text' of undefined

TypeError: Cannot read property '_text' of undefined
    at SAXParser.parser_text [as ontext] (D:\work\2018\08-03\water\App\apps02\node_modules\xmldoc\lib\xmldoc.js:235:39)
    at emit (D:\work\2018\08-03\water\App\apps02\node_modules\xmldoc\node_modules\sax\lib\sax.js:639:35)
    at closeText (D:\work\2018\08-03\water\App\apps02\node_modules\xmldoc\node_modules\sax\lib\sax.js:649:26)
    at emitNode (D:\work\2018\08-03\water\App\apps02\node_modules\xmldoc\node_modules\sax\lib\sax.js:643:26)
    at SAXParser.write (D:\work\2018\08-03\water\App\apps02\node_modules\xmldoc\node_modules\sax\lib\sax.js:1195:15)
    at new XmlDocument (D:\work\2018\08-03\water\App\apps02\node_modules\xmldoc\lib\xmldoc.js:199:15)
    at readManifest (D:\work\2018\08-03\water\App\apps02\node_modules\react-native\local-cli\core\android\readManifest.js:20:10)
    at Object.projectConfigAndroid [as projectConfig] (D:\work\2018\08-03\water\App\apps02\node_modules\react-native\local-cli\core\android\index.js:41:20)
    at Object.keys.forEach.key (D:\work\2018\08-03\water\App\apps02\node_modules\react-native\local-cli\core\index.js:101:36)
    at Array.forEach (<anonymous>)

**Comment by sunnylqm** [comment]
请去 @react-native-community/async-storage 提问
